version: '3.7'

services:
  neuron-telegram-bot:
    build: .
    command: ["npm", "run", "start:dev"]
    init: true
    env_file:
      - .env
    environment:
      LOG_LEVEL: debug
      LOG_FORMATTER: human
    volumes:
      - ./src:/usr/app/src
